### ISSUE TITLE
We have two copies of the privacy page, cookies page, accessibility statement and similar on our website

### ISSUE THREAD

**Issue by lfdebrux** [alphagov/govuk-prototype-kit-docs#101]
### Cause

We decided that we would leave the v12 pages pretty much untouched when we created the v13 pages. However, that means that the old privacy policy, accessibility statement and cookies page are still available at `/v12/docs/...`, and those are different pages from the v13 versions at `/docs/...`.

### Consequences

If we update one set of pages but not the other we could end up with two different accessibility statements. This might be what we want, but that seems unlikely.

### Impact of debt

Medium

### Effort to pay down

Low

**Comment by lfdebrux** [comment]
It would be good to understand whether we need two different copies of each for what reason. @nataliecarey to have a look through and make a recommendation.

**Comment by ruthhammond** [comment]
Closed until this is reported as an issue by users. Will review if significant changes are made to cookies that affect v12
