### ISSUE TITLE
Adding conditional content guidance to tutorials

### ISSUE THREAD

**Issue by harrythompsondwp** [alphagov/govuk-prototype-kit-docs#107]
### Using condition content
As far as I can see there's no good guidance on using conditional content, using nunjucks syntax. But I've used and seen it used in quite a few GDS prototypes, and had to teach myself how to do it. I've written the attached guide for colleagues at Opencast, but I figure this would be a useful addition to the tutorials section of the kit. Happy for any of it to be adapted, but something along these lines would be helpful to include!
[Conditional content.pdf](https://github.com/alphagov/govuk-prototype-kit/files/10058098/Conditional.content.pdf)

**Comment by harrythompsondwp** [comment]
Updated version attached with better guidance on data notation. i.e. {{data['name']}} is better than {{data.name}} as it allows for hyphens in the name tag.
[Conditional content v2.pdf](https://github.com/alphagov/govuk-prototype-kit/files/10086047/Conditional.content.v2.pdf)

**Comment by joelanman** [comment]
related: #110

**Comment by joelanman** [comment]
I think we now have most of this in our guides:
 - https://prototype-kit.service.gov.uk/docs/conditional-content
 - https://prototype-kit.service.gov.uk/docs/pass-data

Thanks @harrythompsondwp for the issue and the content!
