### ISSUE TITLE
v13 docs are duplicated on two different paths

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-prototype-kit-docs#108]
## What

v13 docs are duplicated, they are available here:

https://prototype-kit.service.gov.uk/docs/tutorials-and-examples

and here:

https://prototype-kit.service.gov.uk/v13/docs/tutorials-and-examples

We may want to remove the /v13/ version

## Why

Having duplicate pages is confusing for users and bad for search engines - I'm not sure what the value is of having the duplication, possibly a mistake?

## Who needs to work on this

 - developers

## Who needs to review this

 - developers

## Done when

- [ ] We know if/how we want to de-duplicate
- [ ] Implement any desired changes

**Comment by lfdebrux** [comment]
This was done on purpose, so we'd have a permalink URL to v13 docs that would work both now and in the future when v14 comes out. It shouldn't cause issues with search engines though, the route has`noindex` on it, same as the v12 route (see commit https://github.com/alphagov/govuk-prototype-kit-docs/commit/0ffb68c14701d1a3f739ece67f194f3f1a93bd54).

Regarding issues with users, could you add more detail on the report from the user and how it caused confusion? Is there a way to improve the user experience without getting rid of the functionality?

**Comment by joelanman** [comment]
Ok thanks I wasn't aware we'd done this and was confused. I'm not sure what our user need is for a permalink to v13 docs? What is the advantage over archiving it on a v13 path if and when we need to?

This is not from a report from a user, but if they were to find or get a link to v13 somehow then when we update the link would still go to v13, as opposed to the normal url which gets updated.

**Comment by lfdebrux** [comment]
> Ok thanks I wasn't aware we'd done this and was confused. I'm not sure what our user need is for a permalink to v13 docs? What is the advantage over archiving it on a v13 path if and when we need to?
> 

If we want to write a document that will be around for a long time without getting updated, and we want to link to our docs, and we suspect that the docs page might change in future versions. For instance, if I was writing a git comment about a change to the plugins page, and wanted to link to the docs page for context, I would use the permalink.

> This is not from a report from a user, but if they were to find or get a link to v13 somehow then when we update the link would still go to v13, as opposed to the normal url which gets updated.

Yeah, that's the idea. As above when you would use it depends on the what you're writing.

**Comment by joelanman** [comment]
ok cool thanks
