### ISSUE TITLE
Document how to deal with checkboxes in data

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-prototype-kit-docs#113]
Checkboxes create an array of values.

Simply printing out the values gives a default comma separated list: `a,b,c`

It would be good document how to:

 - use the `| join` filter
 - use a `for` loop
 - check a value is in the array (a user selected a particular checkbox)

**Comment by hannalaakso** [comment]
I think this card is mostly about Nunjucks but related to this, a question came up on support where a user was trying to check in `routes.js` whether the value of checkboxes equalled a certain value. To do this, you first need to check that you're dealing with an array and then check if the array contains the value. 

This seems like a very common use case so it would be good to document it.

**Comment by liammcmurray** [comment]
☝️ It was me.
There is a clickwrap pattern that comes up repeatedly when creating prototypes to test with users, where we have a screen where the user is presented with a condition for continuing and must confirm by checking a box.
I've seen other designers use a yes/no radio set to get around this just for proving the concept, but it'd be better to have documentation and ideally an example with a checkbox that can be used.
Happy to contribute as Hanna and I have thrashed out something decent today.

**Comment by edwardhorsford** [comment]
One way I've dealt with similar things before is to coerce the result to always be in an array - that way when you're checking the answers, the methods are all consistent.

**Comment by joelanman** [comment]
yeh in the prototype kit checkboxes are always an array, or if nothing is selected I guess its undefined or null. So you could have a check which is something like:

```
if (myCheckboxes && myCheckboxes.includes("apple")) {
```

or 

```
if (myCheckboxes){
  if (myCheckboxes.includes("apple")) {
```

**Comment by joelanman** [comment]
just wanted to record a mistake I made on this recently - in JavaScript you *cannot* compare arrays like this:

```
if (myCheckboxes == ["apple"])
```
probably the simplest workaround is to make a compare function:

```
const arraysAreEqual = function(a, b){
  return JSON.stringify(a) == JSON.stringify(b)
}
```
then you can use it:
```
if (arraysAreEqual(myCheckboxes, ["apples"])
```

**Comment by joelanman** [comment]
came up in support today
