### ISSUE TITLE
Make our "next" links better

### ISSUE THREAD

**Issue by domoscargin** [alphagov/govuk-prototype-kit-docs#119]
Currently, our "next" links for documentation are a bit utilitarian:
![The Prototype Kit documentation "next" link - currently just some text that says "Next (link your pages together)" all on one line](https://user-images.githubusercontent.com/22524634/149735028-cacc5514-d7ac-4d0b-acd1-10eaca25fe79.png)

It might be good to explore something like GOV.UK Publishing Components' [Previous and next navigation](https://components.publishing.service.gov.uk/component-guide/previous_and_next_navigation) component instead, as it would make us look more consistent with GOV.UK services.

## Done when

- [x] We have a design for the next links
- [x] Implement the new design

**Comment by joelanman** [comment]
Trying the GOV.UK Pagination component as suggested:

https://design-system.service.gov.uk/components/pagination/
