### ISSUE TITLE
Create branching checkbox example

### ISSUE THREAD

**Issue by terrysimpson99** [alphagov/govuk-prototype-kit-docs#132]
There's a branching example showing radio buttons at ``https://govuk-prototype-kit.herokuapp.com/docs/examples/branching. See: 
![image](https://user-images.githubusercontent.com/48089049/68131405-ea7cff80-ff14-11e9-9944-f9d538880b2c.png)

Please can a similar example be produced showing checkboxes?

**Comment by NickColley** [comment]
Hey Terry,

We're aware of the branching example for radios not being that user friendly so want to improve this in the future, when we do that work we'll keep this in mind.

In the meantime I've put together an example that should help you, the main difference from a code point of view is that when using checkboxes you end up with multiple values to check rather than a single value. This means you can use the `includes` method which I've demonstrated below.

```html
<form action="/docs/examples/branching/fruits" method="post" class="form">
  <div class="govuk-form-group">
    <fieldset class="govuk-fieldset">
    <legend class="govuk-fieldset__legend govuk-fieldset__legend--m">
      <h2 class="govuk-fieldset__heading">
        What fruits do you like?
      </h2>
    </legend>
    <div class="govuk-checkboxes govuk-checkboxes--inline">
      <div class="govuk-checkboxes__item">
        <input class="govuk-checkboxes__input" id="banana" name="fruits" type="checkbox" value="banana">
        <label class="govuk-label govuk-checkboxes__label" for="banana">
          Banana
        </label>
      </div>
      <div class="govuk-checkboxes__item">
        <input class="govuk-checkboxes__input" id="apple" name="fruits" type="checkbox" value="apple">
        <label class="govuk-label govuk-checkboxes__label" for="apple">
          Apple
        </label>
      </div>
      <div class="govuk-checkboxes__item">
        <input class="govuk-checkboxes__input" id="orange" name="fruits" type="checkbox" value="orange">
        <label class="govuk-label govuk-checkboxes__label" for="orange">
          Orange
        </label>
      </div>
    </div>
    </fieldset>
  </div>
  <button class="govuk-button" data-module="govuk-button">Continue</button>
</form>
```

```javascript
router.post('/examples/branching/fruits', function (req, res) {
  let fruits = req.session.data['fruits'] || []

  // If they pick apple or banana then show them the success page
  if (fruits.includes('banana') || fruits.includes('apple')) {
    res.redirect('branching/success')
  } else {
    res.redirect('branching/failure')
  }
})
```

**Comment by joelanman** [comment]
Nick's example logic is `includes` - which means 'banana' and optionally any other checkbox is selected.

~If you want *just* 'banana' and nothing else selected you need:~

~if (fruits == ['banana']) {~

*edit*

Sorry, my code was wrong, you can't compare arrays like that in JavaScript. Here's one of the simpler solutions:

https://stackoverflow.com/a/23555773

**Comment by terrysimpson99** [comment]
This is excellent help, promptly given. Thank you very much. I haven't got it working yet because I have been drawn into other tasks but I'm hopeful of getting it working.

**Comment by ruthhammond** [comment]
@joelanman to consider merging with branching guidance ticket

**Comment by joelanman** [comment]
we now have this guidance!
https://prototype-kit.service.gov.uk/docs/branching-journeys-checkboxes
thanks for raising @terrysimpson99
