### ISSUE TITLE
Make it easier to find support details in docs

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-prototype-kit-docs#135]
Raising this on behalf of a user who couldn't find our contact details in the kit docs. They'd looked at the [main docs page](https://govuk-prototype-kit.herokuapp.com/docs) but had missed the subheading "Get support" under "About" (they eventually got our contact details from a slide deck someone shared with them).

It feels like our support details are important enough to be in their own section like they are on the [Design System homepage](https://design-system.service.gov.uk/).

We could consider not doing anything about this right now and seeing if the issue surfaces again since (to my knowledge) it hasn't been reported before.

**Comment by 36degrees** [comment]
@joelanman do you think this is fixed by alphagov/govuk-prototype-kit#857 ?

**Comment by joelanman** [comment]
@36degrees sorry for the delay! Yeh the new design currently looks like this, with a support link:

![image](https://user-images.githubusercontent.com/1132904/76304772-d7f84580-62bb-11ea-8e28-c91464524253.png)

**Comment by joelanman** [comment]
Support is now in the main nav
