### ISSUE TITLE
Document common ways to do journey branching

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-prototype-kit-docs#141]
The documentation only covers branching journeys using radios. It would be useful to cover in more detail, including checkboxes, and possibly text boxes.

## Who needs to do this work

@joelanman to lead on testing with users

## Who needs to review this work

Content designer PM @ruthhammond 

## Done when

- [x] Guidance has been drafted
- [x] Guidance has been tested with users
- [x] Guidance on common ways to do journey branching has been published

**Comment by oli-rose28** [comment]
@joelanman I made some changes to this here: https://github.com/alphagov/govuk-prototype-kit-docs/tree/improve-branching

Let me know what you think 🙂
