### ISSUE TITLE
Document other methods of setting data

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-prototype-kit-docs#142]
We had a couple of support requests for this scenario: Optionally set data for one journey but not others. Default session data will set the data for all journeys.

There are different ways to do this:

 - in a URL via a link (`/start?name=Joe`)
 - on a page using a form with hidden or visible inputs
 - in routes.js

## Who needs to work on this
- content designer

## Who needs to review this
- interaction designer

## Done when

 - [ ] We have documentation for common ways to set data

**Comment by mazzabodwin-dit** [comment]
I was also unware of the following methods (or have never found/ understood it the guidance!): 
`value: data['my-data'] or 'my-default-data'`

`{{ data['my-data'] or "my-default-data" }}`

`{{ data['my-value'] | default("Fallback text") }}`

**Comment by Izabela-16** [comment]
@joelanman to update the ticket with the template card / issue
