### ISSUE TITLE
Inconsistency in "Next" links for getting started

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-prototype-kit-docs#151]
Just spotted a little inconsistency in the "Next" links when navigating the Getting Started tutorials. Most pages have a [Pagination link](https://design-system.service.gov.uk/components/pagination/#for-smaller-numbers-of-pages) to point to the next page, but not the [Prototype Kit Requirements page](https://prototype-kit.service.gov.uk/docs/install/requirements).

On that page, the link is inline in the text, which makes it a little hard to find.

<img width="723" alt="Screenshot of the Prototype Kit Requirements bottom of the page, where the link to next page is inside the text" src="https://user-images.githubusercontent.com/396367/212052016-baf0b7a4-0e4b-48af-85d3-0e49a0c4480c.png">
<img width="759" alt="Screenshot of the Install Node page, where the link is a Pagination link" src="https://user-images.githubusercontent.com/396367/212052018-5bb917e7-8b5a-4cd7-84ec-ff1d6e41c620.png">

**Comment by joelanman** [comment]
thanks, that's deliberate as pagination is only intended to be on the page once. Here, we sort of have a branching journey for Windows and Mac, each with their own Next links. If it was pagination I think it would be easy for Windows users to click the first big Next link by accident

**Comment by romaricpascal** [comment]
Oh I see, I had missed the "install Node.js" in the Mac part as well 🙈

**Comment by joelanman** [comment]
ha ok I'll have another look at arranging this content

**Comment by romaricpascal** [comment]
Wondering if asking if people are on Windows or Mac to branch ahead of the installation instruction may help keep the flow in a "I click on a big target at the end of the content to move forward" 😄

**Comment by joelanman** [comment]
yeh the issue is there's a lot of shared content here, then a small amount of mac content, large amount of windows content. But I'm sure there's a better approach

**Comment by joelanman** [comment]
we now have fully branching paths per operating system, and consistent Next links
