### ISSUE TITLE
Add GA and cookie consent to the Prototype Kit website

### ISSUE THREAD

**Issue by ruthhammond** [alphagov/govuk-prototype-kit-docs#173]
## What

Add Google Analytics and Cookie consent to the Prototype Kit website

## Why

To collect analytics consistently with other GOV.UK product sites

## Who

Developers

## Done when

- [x] There is a standard cookie consent banner 
- [x] GA collects data only when consent is given via the banner
- [x] [Cookies page is updated](https://prototype-kit.service.gov.uk/docs/cookies)

**Comment by joelanman** [comment]
This work may be affected by GA releasing v4 soon: alphagov/govuk-prototype-kit#1768

**Comment by joelanman** [comment]
Cookie banner:
https://design-system.service.gov.uk/components/cookie-banner/

**Comment by joelanman** [comment]
from meeting with Data services the recommendation is to wait for the new 'lightweight tracking schema' which will be available in April. Alternatively we can go ahead with the old tracking code

**Comment by joelanman** [comment]
@nataliecarey tracking code:
```
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-26179049-11"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-26179049-11');
</script>

```

**Comment by ruthhammond** [comment]
Data doesn't seem to be stored.
