### ISSUE TITLE
Improve tutorials and guides

### ISSUE THREAD

**Issue by oli-rose28** [alphagov/govuk-prototype-kit-docs#177]
**What**

We completed a content review of all of the existing tutorials and guides in the service. There were consistent issues across the service that we can iterate and improve. This ticket is to track those improvements, rather than having lots of tickets on the backlog. 

We will create individual tickets as we are working on the pages to track the actual changes.

**Why**

It makes sense to make our guidance clearer and easier to use for everyone.

**Who needs to work on this**

Content Designer

**Done when**

Each guide:
- explains what technical terms mean
- is clear and easy to understand (this applies more to older guides)
- helps new users to learn advanced topics (some guides feel too concise)
- provides opportunities to learn more about an unfamiliar topic 
- links users to the right place (for example, manage your prototype)
- gives examples of where and why you might use something (make these specific to prototyping government services)

### Pages

**Download and install**
- [x] Getting started on the Prototype Kit
- [x] Prototype Kit requirements
- [x] Create a prototype
- [x] How to run the kit
- [x] Getting started - advanced guide

Drafts here: https://docs.google.com/document/d/1zC5vuqxzB0PXmdVKxIuby8Jj244B-eStCoZFLRvUt34/edit

**Get started**
- [x] Build a basic prototype
- [x] Open your prototype in your editor
- [x] Create pages
- [x] Link your pages together
- [x] Use components from the Design System
- [x] Show the user's answers
- [x] Let the user change their answers
- [x] Show different pages depending on user input (branching)
- [x] Link your index page to your start page

Drafts here: https://docs.google.com/document/d/1OG4Cw8Khw9tFWJ_Dbl2o8mKjWU1nT1xgMGKcTsUUGYY/edit

**Basic usage**
- [x] [How to use layouts ](https://docs.google.com/document/d/1jJmYt1IqgSvLfYL_yqD9n7L3KEy4_AZHMOktjGNKxI0/edit#)
- [x] [Create pages from templates](https://docs.google.com/document/d/1pSq2i1SbQj-W-OTVrBjAiDe52xsLYCTD3-5WgVwnGoc/edit)
- [x] [Install and use plugins](https://docs.google.com/document/d/1yo4VC5VwGLSbrBYJR5UyfLWxWrCvtIIkSUoz0spXfBA/edit)
- [x] [Share usage data](https://docs.google.com/document/d/1bS9rzg0-7URyAXQkUy60wOOZ3k4_aAuHWb3V6-zaDwU/edit)
- [x] [Add CSS, JavaScript, images and other files](https://docs.google.com/document/d/1MVpmF7WcZZ6eYiMwngfDhowophLM7gK6YMr6vr5LqBc/edit)
- [x] [Store your code online with GitHub or GitHub Desktop](https://docs.google.com/document/d/10Ozinc0dXA9Bjdsc-4cunQ3z2GkidWAda_XDwpEyQq0/edit)
- [x] [Set up Git using terminal](https://docs.google.com/document/d/1xMngcf1HyHK68_co5P67lWu-5XJ26ttDQDZZ6seNkJM/edit#)
- [x] [Publish your prototype online](https://docs.google.com/document/d/1xxhK7ounUV2GIGv4jUcFry4iz0ZU7llY3FkJV_CY8rs/edit)
- [x] [Pass data from page to page](https://docs.google.com/document/d/1no3FJt2tvaR5Od_u9CJ4iMqpeHdx5PHWpVXK_dVh6k0/edit#heading=h.sxep9ycdess2)
- [x] [Update to the latest version of the Prototype Kit](https://docs.google.com/document/d/1sJCNeZjf6Q3d3gVhsz7o9opkGu8nR0FVwU2koeILZt0/edit)

All drafts are within this folder: https://drive.google.com/drive/folders/1yy3qBidt9Jeog-Ddfo1z-M_amY5lJ50-

**Advanced usage**
- [x] [Create routes (server side programming)](https://docs.google.com/document/d/11RRovMVo36eWSRRZbmej5v7acj6jHE8pFs9KiuOIuz4/edit)
- [x] [Override the service name on one page](https://docs.google.com/document/d/1qHUQUgdMysecS5ohabCyE25iqc10suATgUmG4QgBYB4/edit)
- [x] [Store data in session](https://docs.google.com/document/d/1W0_0bo9ROgoMkGJOq2xCHrd5om0pEo-QZYrfSGVeJxc/edit)
- [x] [Use GOV.UK Notify to prototype emails and text messages](https://docs.google.com/document/d/1dHkygjOvhcWYutHknkgcqtieBM7fAxUF9k3yG9k1GUY/edit)
- [x] [Template partial areas](https://docs.google.com/document/d/1p4J2tGsb4CeikIeinIlKRTpPV0ovtPt07Z1lFraJZYQ/edit)
- [x] [Migrate an existing prototype to version 13](https://docs.google.com/document/d/1mGXT-pRDY56KFulVHOb30NCl3fK9ns5_cD35PkUfs4U/edit)

All drafts are within this folder: https://drive.google.com/drive/folders/1Zg20_OmrxqxjsbAuvNq9Kij0PAgcOm4F

**Comment by joelanman** [comment]
@joelanman to review
