### ISSUE TITLE
In the Make a prototype tutorial tell users to use the latest version of the kit

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-prototype-kit-docs#185]
The Make a prototype tutorial refers to the latest version of the kit and core plugins. If users do not have the latest version they may get confused

https://prototype-kit.service.gov.uk/docs/make-first-prototype/start

There needs to be a clear statement at the start that the tutorial refers to latest version of the Kit.

**Comment by oli-rose28** [comment]
https://github.com/alphagov/govuk-prototype-kit-docs/pull/196
