### ISSUE TITLE
Plugins - Add documentation for plugins

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-prototype-kit-docs#188]
## What

Add documentation for Plugins

Plugin notes:

https://docs.google.com/document/d/11yuUfSLT47yunW5HHTraBV1KBxbE5cYxO-NNb935Iq0/edit#

Create a plugin guide draft:
https://docs.google.com/document/d/1xLETvJApivoUiBw4enajmEKYp-07ItAQW0O7cBuesws/edit#

PR:
https://github.com/alphagov/govuk-prototype-kit-docs/pull/231

## Why

So people can write and use them

## Who
- Developer (initially for first draft)
- Content designer (for review and refinement)

## Done when

- [ ] documentation for plugin authors
- [ ] review existing documentation for plugin end users
- [ ] research next steps have been agreed

**Comment by paulmsmith** [comment]
This gets an up-vote from me 👍 

At the National Lottery Heritage Fund we are using the prototype-kit 'unbranded'.

## Questions I have:
### How do I use an existing extension with the prototype kit? 
Such as [HMRC Frontend](https://github.com/hmrc/hmrc-frontend)

### How do I create my own organisation/project specific extension?
Am I correct in believing that would more nicely separate the bundled GOVUK Frontend from our organisation specific frontend (assets, styles, scripts)?

### Do extension SCSS files get automatically imported into 'unbranded.scss' or 'application.scss'?
Is there a manual step to import them? (And therefor be in the outputted css file used by the prototype kit?)

### Can I use extensions for something other than a node module?

**Comment by nataliecarey** [comment]
This is my working document https://docs.google.com/document/d/1NrN6GmKDvQLoEEJj_hjSpb8GJNLH8KZqm-1PE1D9d4U

And this is the channel I advise people in which leads into that documentation https://ukgovernmentdigital.slack.com/archives/C044HKGJX1T

**Comment by oli-rose28** [comment]
@ruthhammond @joelanman I've separated out the previous plugin assurance doc and the [Create a plugin draft](https://docs.google.com/document/d/1xLETvJApivoUiBw4enajmEKYp-07ItAQW0O7cBuesws/edit#), as it was getting a little confusing.

@nataliecarey we've put together a structure for the create a plugin guide, which includes a tutorial aspect (create your first plugin) and more technical parts for the package.json and config file. 

Are you able to build on the draft with the technical elements and the example plugin you walked me through before? It would be great to take the user through that process. Thanks!

**Comment by joelanman** [comment]
plugin guidance is now online:

https://prototype-kit.service.gov.uk/docs/create-plugin
