### ISSUE TITLE
Move the instructions for installation of Code Editor earlier in the set up process

### ISSUE THREAD

**Issue by alinagraham** [alphagov/govuk-prototype-kit-docs#199]
## What
Move the instructions for the installation of Code Editor earlier in the set up process 
## Why
As a new user, I want to be able to complete all the installations in one go, so that I know it is complete and I can get on to creating a prototype
## Who needs to work on this
- Content designer
## Done when

- [x] The installation of Code Editor is at a similar stage to the other installations in the tutorial

**Comment by oli-rose28** [comment]
This has been included within the branch: https://github.com/alphagov/govuk-prototype-kit-docs/pull/206#pullrequestreview-1391956388
