### ISSUE TITLE
Explore suitable background reading and other helpful resources/ training

### ISSUE THREAD

**Issue by alinagraham** [alphagov/govuk-prototype-kit-docs#200]
## What
Explore whether there is suitable background reading and other helpful resources and training that could be provided to users to develop their understanding as supplementary material
## Why 
New users lack confidence, particularly in the set up process.
Technical jargon is difficult to understand.
New users do not know some of the basics for using programs such as VS Code
Users are not sure how to open folders within Code editor
## Who needs to work on this
- Content designer
- Interaction designer 
## Done when

- [x] Background reading around background resources completed
- [ ] Users have access to any existing training and background reading that will help them to learn more (if suitable is identified)
- [ ] Gaps identified for new content (separate ticket)

**Comment by oli-rose28** [comment]
I've put together a list of potential resources and background reading in this doc: https://docs.google.com/document/d/1vSlEE4A2lxMqhTc8IRx97qcvAZdi4jknruGvu2f8Hh0/edit#
