### ISSUE TITLE
Improve how users of different operating systems use the tutorials

### ISSUE THREAD

**Issue by alinagraham** [alphagov/govuk-prototype-kit-docs#202]
## What
Improve how users of different operating systems use the tutorials
## Why 
The instructions are more tailored to mac users. 
As a windows user, I want to see more windows specific options, so that I can easily set my prototype up
## Who needs to work on this
- Content designer
- Developer
- Interaction designer 
## Done when

- [ ] All the changes needed for windows users are identified
- [ ] It is as easy for a windows user to follow the tutorials as a mac user

**Comment by oli-rose28** [comment]
https://github.com/alphagov/govuk-prototype-kit-docs/tree/operating-systems

**Comment by oli-rose28** [comment]
@ruthhammond @joelanman @alinagraham @JonJMagee  I've split out the journeys for Windows and Mac within the branch above. I've only got a Mac, so I'm not able to follow the Windows tutorial to see what works and what doesn't. Do we have any ideas on how to tackle this?

**Comment by oli-rose28** [comment]
@joelanman @ruthhammond I think we've done this, so I'll close the ticket.
