### ISSUE TITLE
Version of govuk-prototype-kit downloaded is based on the version number in this repo

### ISSUE THREAD

**Issue by lfdebrux** [alphagov/govuk-prototype-kit-docs#25]
## What

Change the download route to point users to the latest release archive, rather than relying on the version number in the package.json file of this repo.

## Why

Currently the code to create the download link is a legacy from when this site was part of the prototype kit repo. Now the two have been split we probably want a different release process for this site, and to be able to make a release of the kit without having to update this repo.

## Who needs to work on this

Developer

## Who needs to review this

Developer

## Done when

- [ ] We can release a new version of the kit and the docs site points users to it without making any changes to this repo

**Comment by joelanman** [comment]
in v13 there is no download link, closing
