### ISSUE TITLE
Add basic html to the tutorial

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-prototype-kit-docs#253]
## What

Add basic HTML to the tutorial

## Why

The tutorial covers some html, but doesnt explain the basics of tags opening and closing, attributes.

## Who needs to work on this

- content design

## Who needs to review this

 - interaction design

## Done when

- [x] We have covered the basics of html in the tutorial

**Comment by oli-rose28** [comment]
PR: https://github.com/alphagov/govuk-prototype-kit-docs/pull/260
