### ISSUE TITLE
Create deploy process for new Prototype Kit Docs

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-prototype-kit-docs#3]
## What

Create deploy process for new Prototype Kit Docs, based on the Design System deploy process.

We should start by deploying to the current docs URL, https://govuk-prototype-kit.herokuapp.com, to avoid the need to change the code substantially or add a redirect.

However, I would suggest not immediately using govuk-prototype-kit.herokuapp.com, but instead starting with https://govuk-prototype-kit-docs.herokuapp.com, so that we can test the two sites side-by-side for a while, and when we're ready do a 'zero-downtime deploy', switching the app names so traffic is seamlessly switched from one app to another.

## Why

So we can easily and reliably deploy new versions of the Prototype Kit docs.

## Who needs to do this

Developer

## Who needs to review this

Developer

## Done when

- [x] Merges to main are deployed automatically to https://govuk-prototype-kit-docs.herokuapp.com

**Comment by lfdebrux** [comment]
The app govuk-prototype-kit-docs already exists on Heroku, originally owned by @joelanman. He's transferred ownership to design-system-developers@digital.cabinet-office.gov.uk now.

**Comment by lfdebrux** [comment]
To be able to connect Heroku to this repo I had to give the user @govuk-design-system-ci admin access. I noticed that the collaborators on this repo aren't consistent with the collaborators on govuk-prototype-kit, so I'll also fix that now.

**Comment by lfdebrux** [comment]
I also had to change some config vars and turn the app into a pipeline so that we could use review apps, but https://govuk-prototype-kit-docs.herokuapp.com now works, and deploys to main will go there.
