### ISSUE TITLE
Publish new Prototype Kit docs

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-prototype-kit-docs#4]
## What

Publish new Prototype Kit docs at https://govuk-prototype-kit.herokuapp.com.

If we follow the method suggested in https://github.com/alphagov/govuk-prototype-kit-docs/issues/3, this should just be a case of renaming/repointing the two apps.

## Why

So we are serving docs from the app in this repo, rather than from the main repo.

## Who needs to do this

Developer

## Who needs to review this

Developer

## Done when

- [x] The pages hosted at https://govuk-prototype-kit.herokuapp.com are generated from this repo
- [x] Merges to main are deployed automatically to https://govuk-prototype-kit.herokuapp.com/
- [x] https://govuk-prototype-kit-docs.herokuapp.com no longer exists

**Comment by lfdebrux** [comment]
Going to do this now. My plan is

1. Disconnect the Heroku pipeline govuk-prototype-kit from the repo govuk-prototype-kit
2. Connect the Heroku pipeline govuk-prototype-kit to the repo govuk-prototype-kit-docs
3. Rename the Heroku pipeline and app govuk-prototype-kit-docs to govuk-prototype-kit-review
5. Disconnect the Heroku pipeline govuk-prototype-kit-review from the repo govuk-prototype-kit-docs
6. Connect the Heroku pipeline govuk-prototype-kit-review to the repo govuk-prototype-kit
7. Rename the Heroku pipeline govuk-prototype-kit to govuk-prototype-kit-docs (if possible without changing the URL)

**Comment by lfdebrux** [comment]
This went ahead pretty much according to plan :)

https://govuk-prototype-kit.herokuapp.com/docs is now deployed from the code in https://github.com/alphagov/govuk-prototype-kit-docs

https://govuk-prototype-kit-review.herokuapp.com/ is now deployed from the code in https://github.com/alphagov/govuk-prototype-kit
