### ISSUE TITLE
Fix tests on PRs as they keep breaking

### ISSUE THREAD

**Issue by Izabela-16** [alphagov/govuk-prototype-kit-docs#53]
## What
Fix the tests. 

## Why
The last few content PRs the tests have broken for unrelated reasons 

## Who needs to work on this
Developers 

## Who needs to review this
Developers

## Done when

- [ ] We have stable test on this repo

**Comment by lfdebrux** [comment]
Related to #46.

**Comment by joelanman** [comment]
@lfdebrux oh that looks like it covers it more thanks, shall we close this one?
