### ISSUE TITLE
Change guidance to talk about Node 18 when it's released as LTS

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-prototype-kit-docs#58]
## What

Change our guidance to talk about Node 18, not 16, when it becomes LTS (long term support) on the 25 of October

## Why

If we tell people to use 16, it's hard to find. Node's home page always links to the current LTS version

## Who needs to work on this

- content designer

## Who needs to review this

- content designer

## Done when

- [ ] References to Node 16 have been updated to 18 when it becomes LTS

**Comment by joelanman** [comment]
the PR for the last time we did this is here:
https://github.com/alphagov/govuk-prototype-kit/pull/1127

**Comment by lfdebrux** [comment]
Created #62 to address this.
