### ISSUE TITLE
Answer the questions needed for a domain

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-prototype-kit-docs#66]
## What

Questions:

1. [x] What are our nameservers/DNS?
2. [x] What domain do we want?
3. [x] How do users get to the Prototype Kit site from GOV.UK?

## Why

We need to answer these to get a domain

## Who needs to work on this

 - interaction designer
 - content designer
 - developer

## Who needs to review this

 - interaction designer
 - content designer
 - developer

## Done when

- [x] We have answers to the questions

**Comment by joelanman** [comment]
DNS notes:

https://docs.google.com/document/d/1e6C-r7diOtcsJLvqmrr5vwcHZY3PA-NJZvlu_dzhVUQ/edit#heading=h.fhalre5w7w9r

**Comment by joelanman** [comment]
We'd need to set up a redirect app to take people from the old domain to the new one

**Comment by lfdebrux** [comment]
We've agreed that we want to use a CNAME in the GOV.UK DNS service, like Design System, for simplicity.
