### ISSUE TITLE
Redirect users and search engines from the old domain to the new one

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-prototype-kit-docs#70]
## What

Redirect users and search engines from the old domain to the new one

## Why

Users shouldn't get broken links because we've moved domains

## Who needs to work on this

 - developers

## Who needs to review this

 - developers

## Done when

- [x] We are able to redirect users from the old to the new domain

**Comment by lfdebrux** [comment]
We should use 301 permanent redirects for this. 

This is what as Heroku recommends https://devcenter.heroku.com/articles/custom-domains#configuring-dns-for-subdomains, apparently we will still have the `govuk-prototype-kit.herokuapp.com` domain, and can check the `Host` header for the origin. Not sure how SSL works, but oh well 🤷

**Comment by joelanman** [comment]
nice find, just pasting the relevant bit for ease of reference:

>Your app’s Heroku domain always remains active, even if you set up a custom domain. If you want users to use the custom domain exclusively, your app should send [HTTP status 301 Moved Permanently](https://datatracker.ietf.org/doc/html/rfc2616#section-10.3.2) to tell web browsers to use the custom domain. The Host HTTP request header field will show which domain the user is trying to access; send a redirect if that field is example.herokuapp.com.

**Comment by lfdebrux** [comment]
I don't think we can pick this up until we've done #71.

**Comment by lfdebrux** [comment]
Questions: do we want to redirect from the old URL to the new (v13) docs, or the old (v12) docs? And are we happy with a 301 redirect, so people will be able to keep using and sharing the old URL without necessarily realising that the site has moved?

**Comment by joelanman** [comment]
- to the new docs, so I think just a domain replace with the same path should work
- yeh 301 is fine, usage of the old domain will die out over time and the redirect will work in the meantime. For a single or small number of pages it might be nice to explain why something has moved (eg the concept has changed) but for a whole site I think just redirect
