### ISSUE TITLE
Add a warning banner to v12 docs

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-prototype-kit-docs#79]
## What

Add a warning banner to ever page of v12 docs as per the Figma design:

https://www.figma.com/file/sWnqT4u4uup91TuTe9T3tp/GOV.UK-Prototype-Kit-information?node-id=163%3A2

## Why

Users need to know they are looking at an old version of the site and a newer one is available

## Who needs to work on this

- developer

## Who needs to review this

- developer

## Done when

- [x] Visual design is confirmed by designer
- [x] Banner shows on every page of v12 docs

**Comment by lfdebrux** [comment]
@joelanman where should the link in the banner take the user?

**Comment by joelanman** [comment]
I think to the home page.

**Comment by lfdebrux** [comment]
@joelanman do we want the banner on the example template pages, for example https://prototype-kit-docs-v13.herokuapp.com/v12/docs/templates/question

**Comment by joelanman** [comment]
hmm great question.. if its at all hard, I wouldn't bother for now we can always come back to it

**Comment by lfdebrux** [comment]
> hmm great question.. if its at all hard, I wouldn't bother for now we can always come back to it

Not hard at all, just wanted to check what your design intent was.

**Comment by joelanman** [comment]
ok cool then add it thanks!

**Comment by lfdebrux** [comment]
PR for this change is at https://github.com/alphagov/govuk-prototype-kit-docs/pull/83.

Preview is viewable at https://prototype-kit-docs-pr-83.herokuapp.com/v12/docs.
