### ISSUE TITLE
Add a section on the home page linking to what's new in v13

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-prototype-kit-docs#86]
## What

Add a section on the home page linking to what's new in v13. 

## Why

v13 is a big new release and users need to understand what's changed

## Who needs to work on this

 - interaction designer
 - content designer
 - developer

## Who needs to review this

 - interaction designer
 - content designer
 - developer

## Done when

- [x] Content for new page drafted
- [x] Home page update designed
- [x] Home page update implemented
- [x] New page created 
- [x] New page linked to home page

**Comment by ruthhammond** [comment]
@joelanman please add link to design

**Comment by joelanman** [comment]
design here (internal):
https://www.figma.com/file/sWnqT4u4uup91TuTe9T3tp/GOV.UK-Prototype-Kit?node-id=163%3A2&t=5Iar9tBFbcFhEFRs-0
