### ISSUE TITLE
Download link is broken on page 'How to install the kit'

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-prototype-kit-docs#88]
The install link on this page is broken

https://govuk-prototype-kit.herokuapp.com/docs/install/install-the-kit

**Comment by lfdebrux** [comment]
Specifically, the link in the breadcrumb, `href=./install`

**Comment by lfdebrux** [comment]
Also needs to be fixed on other pages at `/docs/install/*`

**Comment by joelanman** [comment]
sorry I wasnt specific I meant `download it as a zip` but the one you mentioned is broken too
