### ISSUE TITLE
Page templates cannot use Nunjucks in Markdown pages, and vice versa

### ISSUE THREAD

**Issue by lfdebrux** [alphagov/govuk-prototype-kit-docs#92]
### Cause

We only render pages using Markdown or Nunjucks, not both.

### Consequence

We can't use Nunjucks macros or includes in Markdown pages, which makes writing them harder, as we don't get benefits of reusability and centralisation.

### Impact of debt

Medium

Makes some things a lot harder, but for most pages it's fine

### Effort to pay down

Medium/High

Would be straightforward to do with Express, although would probably require a lot more code. Alternatively migrating the backend that supported multiple renderers out of the box would solve the problem in a better way, but be much more effort.

**Comment by joelanman** [comment]
I think it's worth redesigning the docs on a proper production stack like Eleventy, that would also tackle this issue and #93

**Comment by joelanman** [comment]
I think this was fixed in #126
